name: Automatic Rebase

on:
  pull_request:
    types: ["labeled", "opened", "synchronize", "reopened"]
    branches-ignore: ["wip/**", "test/**"]

  #   - cron: "0 0 * * 1-5" scheduler never works
  # https://crontab.cronhub.io/ https://crontab.guru

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  rebase:
    if: contains(github.event.pull_request.labels.*.name, 'auto-rebase')

    name: Rebase
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    # env:
    #   BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.7
        # with:
        #   autosquash: ${{ contains(github.event.comment.body, '/autosquash') || contains(github.event.comment.body, '/rebase-autosquash') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
